# Reusable Quality Workflow
name: _Quality

on:
  workflow_call:

jobs:
  code-quality:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Biome
        uses: biomejs/setup-biome@v1
        with:
          version: 1.3.3
      - name: Run Biome
        run: biome ci .